version: '3'
services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/frontend/src
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - WATCHPACK_POLLING=true

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/src:/backend/src
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mydb
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  postgres-data: