version: '3.8'

services:
  client:
    build:
      context: ./client
    volumes:
      - ./client/src:/client/src
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - ENV=DEV
      - WATCHPACK_POLLING=true

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/src:/app/src
    environment:
      - ENV=DEV
      - DATABASE_NAME=node-boilerplate
      - DATABASE_URI=mongodb://db:27017
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    image: mongo:7.0.3-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    environment:
      - MONGO_INITDB_DATABASE=node-boilerplate

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - client
      - backend

volumes:
  dbdata: