# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text_embedding.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14text_embedding.proto\x12\x11text_to_embedding\"\x1c\n\x0bTextRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"E\n\x11\x45mbeddingResponse\x12\x30\n\nembeddings\x18\x01 \x03(\x0b\x32\x1c.text_to_embedding.Embedding\"\x1a\n\tEmbedding\x12\r\n\x05value\x18\x01 \x03(\x02\x32\x64\n\x0fTextToEmbedding\x12Q\n\x07\x43onvert\x12\x1e.text_to_embedding.TextRequest\x1a$.text_to_embedding.EmbeddingResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_embedding_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TEXTREQUEST']._serialized_start=43
  _globals['_TEXTREQUEST']._serialized_end=71
  _globals['_EMBEDDINGRESPONSE']._serialized_start=73
  _globals['_EMBEDDINGRESPONSE']._serialized_end=142
  _globals['_EMBEDDING']._serialized_start=144
  _globals['_EMBEDDING']._serialized_end=170
  _globals['_TEXTTOEMBEDDING']._serialized_start=172
  _globals['_TEXTTOEMBEDDING']._serialized_end=272
# @@protoc_insertion_point(module_scope)
